language: c

jobs:
  include:
  - compiler: clang
    os: linux
  - compiler: gcc
    os: linux
  - compiler: clang
    os: osx
    osx_image: xcode11.4
  - compiler: gcc
    os: osx
    osx_image: xcode11.4

addons:
  apt:
    packages:
    - libiodbc2-dev
  homebrew:
    packages:
    - libiodbc

before_script:
  - autoreconf -i -f -Wno-portability

script:
  - ./configure --disable-man --disable-silent-rules --disable-glib --with-iodbc=/usr
  - make
  - ./src/util/mdb-array test/data/ASampleDatabase.accdb "Asset Items"
  - ./src/util/mdb-array test/data/nwind.mdb "Customers"
  - ./src/util/mdb-count test/data/ASampleDatabase.accdb "Asset Items"
  - ./src/util/mdb-count test/data/nwind.mdb "Customers"
  - ./src/util/mdb-prop test/data/ASampleDatabase.accdb "Asset Items"
  - ./src/util/mdb-prop test/data/nwind.mdb "Customers"
  - ./src/util/mdb-schema test/data/ASampleDatabase.accdb
  - ./src/util/mdb-schema test/data/nwind.mdb
  - ./src/util/mdb-tables test/data/ASampleDatabase.accdb
  - ./src/util/mdb-tables test/data/nwind.mdb
  - ./src/util/mdb-ver test/data/ASampleDatabase.accdb
  - ./src/util/mdb-ver test/data/nwind.mdb
  - env MDBPATH=test/data ./src/odbc/unittest
