language: c

jobs:
  include:
  - compiler: clang
    os: linux
  - compiler: gcc
    os: linux
  - compiler: clang
    os: osx
    osx_image: xcode11.4
  - compiler: gcc
    os: osx
    osx_image: xcode11.4

before_script:
  - autoreconf -i -f

script:
  - ./configure --disable-man --disable-silent-rules
  - make
