version: 0.1.{build}

os: Windows Server 2012 R2

platform: x64

environment:
  matrix:
  - TOOLCHAIN: "msys2"
  - TOOLCHAIN: "cygwin"

branches:
  only:
    - master

clone_folder: c:\projects\mdbtools

skip_tags: true

build_script:
  - ps: |
      if ($env:TOOLCHAIN -eq "msys2")
      {
        $env:MSYSTEM="MINGW64"
        C:\msys64\usr\bin\bash -l -c "pacman -S --noconfirm autoconf-archive mingw-w64-x86_64-glib2"
        C:\msys64\usr\bin\bash -l -c "cd /c/projects/mdbtools && autoreconf -i -f"
        C:\msys64\usr\bin\bash -l -c "cd /c/projects/mdbtools && ./configure --disable-man --disable-silent-rules"
        C:\msys64\usr\bin\bash -l -c "cd /c/projects/mdbtools && make"
      }
      else
      {
        C:\cygwin64\setup-x86_64.exe -qP autoconf-archive libglib2.0-devel
        C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/mdbtools && autoreconf -i -f"
        C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/mdbtools && ./configure --disable-man --disable-silent-rules"
        C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/mdbtools && make"
      }

test_script:
  - ps: |
      if ($env:TOOLCHAIN -eq "msys2")
      {
        $env:MSYSTEM="MINGW64"
        C:\msys64\usr\bin\bash -l -c "cd /c/projects/mdbtools && ./src/util/mdb-count ./test/data/nwind.mdb Customers"
      }
      else
      {
        C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/mdbtools && ./src/util/mdb-count ./test/data/nwind.mdb Customers"
      }
